name: Checkov SCA Scanning

# 1. The "on" property defines what triggers the workflow
on:
  push:
    branches: [ main ]

# 2. The "jobs" property contains the execution logic
jobs:
  prisma_scan_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Checkov SCA Scanning
        id: checkov
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
        with:
          framework: sca_package
          api-key: ${{ secrets.BC_API_KEY }}
